require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.helpers"

-- Plugin Settings
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.toggleterm"
require "user.nvimtree"
require "user.ctrlsf"
require "user.fzf"
require "user.lightline"
require "user.nerdtree"
require "user.vim-commentary"
require "user.vim-test"
