require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.helpers"

-- Plugin Settings
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.toggleterm"
require "user.nvimtree"
require "user.ctrlsf"
require "user.fzf"
require "user.lightline"
require "user.comment"
require "user.vim-test"
require "user.autopairs"
require "user.gitsigns"
require "user.easy-align"
require "user.vim-move"
require "user.vim-slim"
