require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.helpers"

require "plugins.comment"
require "plugins.ctrlsf"
require "plugins.easy-align"
require "plugins.fzf"
require "plugins.gitsigns"
require "plugins.lightline"
require "plugins.nvimtree"
require "plugins.toggleterm"
require "plugins.vim-move"
require "plugins.vim-test"
